backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Produtos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "name", widget: "string" }

  - name: "blogs"
    label: "Blogs"
    folder: "content/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
