backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "content/blogs"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "products"
    label: "Produtos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Preço", name: "price", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
